# Generated by Django 5.1.4 on 2025-01-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0004_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=50)),
        ),
    ]
